version: '3.8'
services:
  neotech-homework-db:
    restart: always
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=neotech_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    container_name: 'neotech-homework-db'