info:
  app:
    name: Neotech homework
    version: 1.0
    description: API Documentation
    active-profile: ${spring.profiles.active}
    dev-description: Spring Boot application that allows detect phone numbers country dial-in codes
    dev-link: https://github.com/ximtech/neotech-homework

server:
  port: 8088
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: "neotech-homework"
  profiles:
    active: ${PROFILE:dev}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: false
    
  thymeleaf:
    enabled: true
    check-template: true
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    hikari:
      minimum-idle: 1
      idle-timeout: 10000
      maximumPoolSize: 2

  flyway:
    enabled: true
    locations: classpath:/db/migration
    default-schema: neotech

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
        
# actuator
management:
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, caches, mappings
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    caches:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      phone-api-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      phone-api-service:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      phone-api-service:
        timeoutDuration: 5s
        cancelRunningFuture: false
        
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    
wiki.phone.country.source.url: "https://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_order"