name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code 
      uses: actions/checkout@v4

    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'

    - name: Build And Run Integration Tests
      run: gradle clean build --info --stacktrace

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ximtech/neotech-homework
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: gradle bootBuildImage --info --stacktrace

    - name: Tag docker image
      run: docker tag neotech-homework ${{ secrets.DOCKERHUB_USERNAME }}/neotech-homework:latest

    - name: Push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/neotech-homework:latest